server.port: 8080
server.error.include-message: always

spring:
  jpa.hibernate.ddl-auto: update # Strongly recommend to set this property to "none" in a production environment!
  datasource:
    url: jdbc:mysql://localhost/customer-service-db
    username: user
    password: pwd
    hikari:
      initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.cat: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring.config.activate.on-profile: docker

spring:
  datasource:
    url: jdbc:mysql://mysql/customer-service-db
    username: user
    password: pwd